# Generated by cpp11: do not edit by hand

compressToEncodedURIComponent_ <- function(uncompressed8) {
  .Call(`_lzstringr_compressToEncodedURIComponent_`, uncompressed8)
}

decompressFromEncodedURIComponent_ <- function(compressed8) {
  .Call(`_lzstringr_decompressFromEncodedURIComponent_`, compressed8)
}

compressToBase64_ <- function(uncompressed8) {
  .Call(`_lzstringr_compressToBase64_`, uncompressed8)
}

decompressFromBase64_ <- function(compressed8) {
  .Call(`_lzstringr_decompressFromBase64_`, compressed8)
}
