# Generated by cpp11: do not edit by hand

compressToEncodedURIComponent_ <- function(bytes) {
  .Call(`_lzstringr_compressToEncodedURIComponent_`, bytes)
}

decompressFromEncodedURIComponent_ <- function(bytes) {
  .Call(`_lzstringr_decompressFromEncodedURIComponent_`, bytes)
}

compressToBase64_ <- function(bytes) {
  .Call(`_lzstringr_compressToBase64_`, bytes)
}

decompressFromBase64_ <- function(bytes) {
  .Call(`_lzstringr_decompressFromBase64_`, bytes)
}
