# Workflow derived from https://github.com/rstudio/shiny-workflows
#
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Package checks

jobs:
  routine:
    uses: rstudio/shiny-workflows/.github/workflows/routine.yaml@v1
  R-CMD-check:
    uses: rstudio/shiny-workflows/.github/workflows/R-CMD-check.yaml@v1
